### ISSUE TITLE
v23后续版本设备限制问题

### ISSUE THREAD

**Issue by Goojoe** [chase535/turbo-charge#62]
我的手机是Motorola Edge X30，只有v23版本可以使用。后续都无法安装，请问为什么加入机型限制呢？

**Comment by chase535** [comment]
不算是机型限制，是为了确保安装上的手机能够真正有用，所以加上了文件存在检测。如果所有文件都不存在，那即使安装上了，程序也毫无作用，只是一个空壳程序一次又一次的陷入while循环而没有做任何事情，一定程度上也会造成系统资源的无用浪费


诺鸡鸭
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chase535/turbo-charge"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月9日(星期四) 下午4:58
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[chase535/turbo-charge] v23后续版本设备限制问题 (Issue #62)





 
我的手机是Motorola Edge X30，只有v23版本可以使用。后续都无法安装，为什么加入机型限制呢？

**Comment by Goojoe** [comment]
Q1:那为什么v23版本可用呢？
Q2:如何提交适配机型？找充电系统文件吗？

**Comment by chase535** [comment]
A1:因为之前的版本并没有注意到这个问题，导致大量路人安装之后没有任何效果，在评论区阴阳怪气甚至是诋毁谩骂，不得不加入此限制。新版已经减少所有文件的必要性，只有当所有功能都不可用时才安装失败，如果还因为缺少文件导致功能失效或者安装不上而阴阳怪气的话，我只能说我永远不会去回答他们的任何问题，有能力就去拉内核源码自己去修改内核，或者去Android研发团队内部工作制定规定取消相关的内核级限制。我没有时间去修改每一个手机的内核，也没有能力去Google工作，我只是一个对编程有兴趣的普通大学生罢了
A2:需要提交文件，但目前来看电流文件、阶梯式充电文件均已找全，如果还是不支持的话真的就是内核的限制了，是内核直接读取硬件数据进行相应操作，而不是读取数据后写入系统文件，再通过读取文件的数据进行相应操作。电量控制功能需要找的文件是能够控制充电启停的文件，此文件应该不会全权交给内核处理，毕竟系统应该也是有此类功能的，必须要用到这些文件，所以即使提示不支持，手机中也可能会有这类文件，只是我不知道这类文件是什么，所以也就无从适配。因为每个温度传感器的灵敏度、所在的区域不同，所以各个传感器的值会有很大的不同（比如我手机的CPU内部温度传感器在高负载时甚至会到达100℃+），而又因为每个手机所拥有的温度传感器不一样，所以我只能挑几个大部分手机都有的、数值与体感温度差异不那么大的传感器，这就导致了某些手机会提示找不到相关传感器

**Comment by Goojoe** [comment]
A1了解

A2：最近有一个新项目KernelSU，目前还是早期版本，如果后续稳定，应该可以提供内核接口以供修改。
这样应该就不用找充电文件了，适配性应该能大大提高

充电文件是怎么找的能给个示例说说吗？
比如某一款机型，系统，文件内容

**Comment by chase535** [comment]
KernelSU确实是一个能够直接操作内核的好项目，但是随着大学生涯进入尾声，我已经不能把时间精力投入在这些事情上了，现在摆在眼前的是提升专业能力、考证、考研、实习、毕设、毕业论文答辩等等很重要且十分耗时耗力的事情，而这些事情忙完后，又会进入读研或者工作这个新阶段，依旧没有时间去弄这些事情，这也就是为什么我会在寒假期间把程序尽可能的完善，因为过了这个寒假我就一点时间都没有了。不过我相信，等待KernelSU成熟之时，定会有很多优秀的模块（姑且这么叫）制作者带着优秀的模块接踵而至，那时将会是又一个搞机的春天。


小米10至尊纪念版，MIUI13，充电电流文件、阶梯式充电文件、充电启停文件均在`/sys/class/power_supply`目录内
1.目前已知充电电流文件：名字包含charge_current、input_current、current_max等字段。**不包括current_max、pd_current_max等文件，这些既有内核限制又有硬件限制，即使改了文件内容也不会有用。**文件内容为充电的最大电流，单位μA。如：`/sys/class/power_supply/battery/constant_charge_current_max`
2.目前已知阶梯式充电文件：名字包含step_charge，文件内容为阶梯式充电的启用情况，0为禁用1为启用，与手机的阶梯式充电开关状态保持一致。如：`/sys/class/power_supply/battery/step_charging_enabled`
3.目前已知充电启停文件：名字包含charge_enabled、input_suspend等字段，文件内容为充电启停情况，0为禁止充电1为允许充电。如：`/sys/class/power_supply/battery/charging_enabled`
4.温度传感器，终端执行下面命令后，就会显示当前手机所拥有的的温度传感器及它的值
`for&nbsp;i&nbsp;in&nbsp;$(ls&nbsp;/sys/class/thermal&nbsp;|&nbsp;grep&nbsp;"thermal_zone");&nbsp;do
&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;[[&nbsp;-f&nbsp;"/sys/class/thermal/${i}/type" &amp;&amp; -f "/sys/class/thermal/${i}/temp"&nbsp;]];&nbsp;then
&nbsp; &nbsp; &nbsp; &nbsp; cat&nbsp;/sys/class/thermal/${i}/type&nbsp;2&gt;/dev/null
&nbsp; &nbsp; &nbsp; &nbsp; cat&nbsp;/sys/class/thermal/${i}/temp 2&gt;/dev/null
&nbsp;&nbsp;&nbsp;&nbsp;fi
done`

**Comment by Goojoe** [comment]
好的,谢谢解答,那么简介说的提交适配是什么意思?
1. 我提交一些文件供你分析?
2. 我找到已分析完充电文件并提供?
3. 写代码适配?

是如何适配一款机型的?

如果不行的话我就不麻烦你了,v23版本也能用

**Comment by chase535** [comment]
A3:2或者3，因为我也分析了很多不适配手机的文件，可是真的找不到有关文件，这真的需要亲自上手然后不同情况多次比对每一个文件才能知道有没有相关文件

A4:程序框架经过几十个版本迭代后已经完善，找到文件后适配很容易

1.电流文件有关代码如下，为了确保能够正确找到所有的文件，就用了正则表达式查找文件，将文件名称转换成正则表达式形式添加进匹配规则并用逻辑或符号`|`相连即可
https://github.com/chase535/turbo-charge/blob/ea494d561d7c698e1ace208aed3e94e6fe8a4e11/turbo-charge.c#L380

2.充电启停文件及阶梯式充电文件均使用了文件的绝对路径而非使用正则表达式匹配，其中

(1)充电启停文件有关代码如下，根据每个文件的作用不同，启停充电的值也不同。如161-162行的文件，1为充电0为不充电，而`if else`逻辑中的文件则刚好相反。如找到新的文件，复制新建一行set_value命令，将引号内的字符串改为文件路径，并将此行命令添加到正确的位置即可
https://github.com/chase535/turbo-charge/blob/ea494d561d7c698e1ace208aed3e94e6fe8a4e11/turbo-charge.c#L159-L173

(2)阶梯充电有关代码如下，，如果新的文件值1为开启0为关闭，则复制新增一行，将引号内的字符串改为文件路径即可，如果0为开启1为关闭则需要像上面的代码那样添加一个`if else`判断
https://github.com/chase535/turbo-charge/blob/ea494d561d7c698e1ace208aed3e94e6fe8a4e11/turbo-charge.c#L259

另外，安装脚本中也有判断文件是否存在的代码，每新增一个文件路径，安装脚本中也要做相应的增加，否则安装时不会判断此文件
https://github.com/chase535/turbo-charge/blob/ea494d561d7c698e1ace208aed3e94e6fe8a4e11/module/install.sh#L51-L113

**Comment by chase535** [comment]
如果找到了能用的版本，那使用那个版本就行，不必追求最新版，毕竟虽然更新很勤，但没有十分重大的改动。新版目前也因为某些玄学因素导致部分手机会有充电缓慢的bug

**Comment by chase535** [comment]
期待KernelSU时代的到来。阶梯式充电对充电速度的影响预估7分钟左右，毕竟最后阶段电流会降低一大截，以增加电池的寿命。之前手机都是可以随意开关阶梯充电，但近几年很多机型都不能关闭了，或许是为了防止大电流带来的快速老化导致大量用户在保修期内白嫖很多次电池，才不让用户关闭阶梯充电

**Comment by Goojoe** [comment]
好的，感谢耐心解答，学到了。
继续等待KernelSU时代吧
