### ISSUE TITLE
添加旁路供电功能

### ISSUE THREAD

**Issue by iyutong** [chase535/turbo-charge#74]
![Screenshot_2023-04-23-20-57-47-845_com omarea vtools](https://user-images.githubusercontent.com/84581911/233841149-ecc4b872-59e8-4a6f-b0ea-6f354174170c.jpg)
能不能与这个共存

**Comment by chase535** [comment]
感谢提问，两者都是通过修改充电电流来达到效果的，所以无法共存。


充电加速不会加入旁路充电功能，因为c语言无法直接获取linux的进程，我知道的实现方法有两种：第一种是直接遍历/proc目录下所有文件夹中的status文件；第二种是直接使用popen创建管道执行shell命令并获取返回值。


第一种方法因为涉及到了遍历和读取文件，且因为文件的数量达到了“万”的级别，所以程序执行效率会大幅下降，再加上c语言只能由此判断程序是否在运行而无法判断程序是否在前台，所以无法实现旁路充电。第二种方法虽然能够获取所需数据，但shell是解释型语言，执行效率比c语言等编译型语言低很多，所以也会直接造成程序整体执行效率的大幅下降。



旁路充电在加速充电模块中属于非必需功能，而我不会为了这一个额外功能而使程序的执行效率大幅下降，因为这与我的理念相违背。



无论是何种语言做的何种程序，包括我在学校做的STM32的各种项目，程序的执行效率是我十分看重的一个指标。为了完全删掉充电加速v6版本中的popen管道通信使程序执行效率大幅提高，我才会在停更很长时间后又重新维护这个模块，为此我花费了大量的时间，几乎重写了整个程序。

**Comment by iyutong** [comment]
你也说到了，都是通过控制电流来实现的，那能不能添加开关，当温度达到多少度时，这个模块停止工作，把电流控制权限交给其他模块，这样你不需要开发旁路供电，只需要让用户另外安装一个旁路供电模块就可以了，因为到达多少度时这个模块停止工作，旁路供电模块一般是到达多少度时开始工作，这样不就可以实现用户想用的功能了吗？你也不需要过多的修改原来的程序。


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月23日(周日) 晚上9:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chase535/turbo-charge] 是否支持与旁路供电同时运行 (Issue #74)




 感谢提问，两者都是通过修改充电电流来达到效果的，所以无法共存。 
 
 
 充电加速不会加入旁路充电功能，因为c语言无法直接获取linux的进程，我知道的实现方法有两种：第一种是直接遍历/proc目录下所有文件夹中的status文件；第二种是直接使用popen创建管道执行shell命令并获取返回值。 
 
 
 第一种方法因为涉及到了遍历和读取文件，且因为文件的数量达到了“万”的级别，所以程序执行效率会大幅下降，再加上c语言只能由此判断程序是否在运行而无法判断程序是否在前台，所以无法实现旁路充电。第二种方法虽然能够获取所需数据，但shell是解释型语言，执行效率比c语言等编译型语言低很多，所以也会直接造成程序整体执行效率的大幅下降。 
 
 
 
 旁路充电在加速充电模块中属于非必需功能，而我不会为了这一个额外功能而使程序的执行效率大幅下降，因为这与我的理念相违背。 
 
 
 
 无论是何种语言做的何种程序，包括我在学校做的STM32的各种项目，程序的执行效率是我十分看重的一个指标。为了完全删掉充电加速v6版本中的popen管道通信使程序执行效率大幅提高，我才会在停更很长时间后又重新维护这个模块，为此我花费了大量的时间，几乎重写了整个程序。 
&mdash;

**Comment by chase535** [comment]
虽然添加这个判断所需的代码量很少，但会让整个程序的逻辑复杂很多。充电加速已经有温度墙功能，如果再加上通过判断温度来让其他程序接管是否不向电池充电这个功能，就属于功能的重叠了，因为程序已经实现了到达一定温度后降低到自定义的充电电流，想要实现到达一定温度后停止充电只需将撞到温度墙后的充电电流改为0即可

**Comment by chase535** [comment]
后续会实现多进程，其中子进程专门获取前台应用数据，然后将数据返回给主进程。配置文件中添加旁路供电功能，如果开启，主进程可以通过判断子进程返回的数据来判断是否向电池充电。但因为我用不到这个功能再加上会造成系统资源的浪费，所以这个功能的优先级很低。

**Comment by iyutong** [comment]
在哪下载？


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月2日(周五) 晚上11:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chase535/turbo-charge] 添加旁路供电功能 (Issue #74)




 
试试Action的最新版，给一下反馈
 
&mdash;

**Comment by chase535** [comment]
https://github.com/chase535/turbo-charge/suites/13343156972/artifacts/729484577

**Comment by chase535** [comment]
长时间未收到反馈，先发布新版，这个issue就先close了，有问题再开一个新的
