### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by iyutong** [chase535/turbo-charge#81]
希望安装更新的时候不重置配置文件

**Comment by chase535** [comment]
有此意向，但如果这样的话就不能在安装的时候通过音量键选择了，两者互相冲突

**Comment by iyutong** [comment]
可以开发一个软件，在软件里面设置，正好你添加的新功能需要设置应用包名，有单独的应用程序去设置这些东西就非常省事了。


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月10日(周六) 下午3:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chase535/turbo-charge] 提个建议 (Issue #81)




 有此意向，但如果这样的话就不能在安装的时候通过音量键选择了，两者互相冲突 
&mdash;

**Comment by chase535** [comment]
但最大问题就在这，我是干嵌入式底层开发的，给我时序图引脚图啥的我能手搓驱动程序，但是前端是一点都不会...很早之前就想过做成一个app，android studio也安装完了，然而安装完后就毫无头绪，已经吃灰两年多...目前的设想是安装时不再使用音量键选择，安装时读取手机上的配置文件，对于那些开关的配置读取到值后显示相应的“原配置文件中xxx功能的值为xxx，功能已打开/关闭”

**Comment by iyutong** [comment]
那等我放假以后，有时间我写一个吧。


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月10日(周六) 下午4:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chase535/turbo-charge] 提个建议 (Issue #81)




 但最大问题就在这，我是干嵌入式底层开发的，给我时序图引脚图啥的我能手搓驱动程序，但是前端是一点都不会...很早之前就想过做成一个app，android studio也安装完了，然而安装完后就毫无头绪，已经吃灰两年多...目前的设想是安装时不再使用音量键选择，安装时读取手机上的配置文件，对于那些开关的配置读取到值后显示相应的“原配置文件中xxx功能的值为xxx，功能已打开/关闭” 
&mdash;

**Comment by chase535** [comment]
可以，麻烦你了。暂时先按我说的改成取消音量键吧

**Comment by iyutong** [comment]
嗯


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月10日(周六) 晚上8:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chase535/turbo-charge] 提个建议 (Issue #81)




 可以，麻烦你了。暂时先按我说的改成取消音量键吧 
&mdash;

**Comment by chase535** [comment]
已实现
