### ISSUE TITLE
小米12  配置文件找不到

### ISSUE THREAD

**Issue by xiang473535976** [chase535/turbo-charge#84]
![Screenshot_2023-06-14-11-18-52-360_bin mt plus](https://github.com/chase535/turbo-charge/assets/18111614/9b7a1c81-f728-4555-a931-ba9977181d8b)
 小米12   充电控制无效，大佬 请问需要提供哪些文件给你，
qq  473535976

**Comment by chase535** [comment]
问题就在这，我也不知道需要哪些文件。。。之前收集过很多不适配的手机的各种文件，但是发现并没有需要的文件，而且没有的很彻底，所以我也无从下手，不能适配。。。

**Comment by baidalan110** [comment]
marble（note12t/f5）配置文件是不是换地方了

**Comment by baidalan110** [comment]
![Screenshot_2024-01-16-21-30-33-285_bin mt plus](https://github.com/chase535/turbo-charge/assets/137660900/c91b0002-d46f-4c76-95d5-dc3d6c85c09d)
![Screenshot_2024-01-16-21-30-36-974_bin mt plus](https://github.com/chase535/turbo-charge/assets/137660900/e948d25c-fcbd-45b8-9d16-e07ec8720c30)

**Comment by baidalan110** [comment]
[温控.zip](https://github.com/chase535/turbo-charge/files/14318601/default.zip)
k70充电温控，通过酷安米安号丢了的那个移除快充温控获取
