### ISSUE TITLE
这个模块支持KernelSU吗？

### ISSUE THREAD

**Issue by iyutong** [chase535/turbo-charge#87]
### 你的请求是否与某个问题相关？

模块兼容KernelSU吗？

### 描述你想要的解决方案

兼容KernelSU

**Comment by chase535** [comment]
目前没有，比完电赛后会考虑

**Comment by chase535** [comment]
看了一下官方文档，除了安装脚本需要进行修改之外没有其他需要修改的地方，[turbo-charge](https://github.com/chase535/turbo-charge/suites/15530011161/artifacts/886447317)试试这个

**Comment by iyutong** [comment]
哦，对了，问个事，就是，我用的小米的充电宝，他是支持pd快充的（手机也小米的），手机显示快充了，但是不走快充协议，不用你的模块手机根本充不进电，用了充电速度上去了但是依然没有启用pd快充，这是为什么？手机支持33W，充电宝支持22.5W，用usb口最高18W，但是实际就11W。


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月27日(周日) 晚上6:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chase535/turbo-charge] 这个模块支持KernelSU吗？ (Issue #87)




 
看了一下官方文档，除了安装脚本需要进行修改之外没有其他需要修改的地方，turbo-charge试试这个
 
&mdash;

**Comment by chase535** [comment]
这我确实也没遇到过，不知道为什么，不过看起来像是尾插坏了...用充电器是正常的吗？如果充电器正常那有可能是充电宝是QC协议的18w，而手机是PD协议的18w，导致了无法用18w充电，换一个支持更多协议的充电宝试试？

**Comment by iyutong** [comment]
用充电器一切正常


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月29日(周二) 晚上9:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chase535/turbo-charge] 这个模块支持KernelSU吗？ (Issue #87)




 这我确实也没遇到过，不知道为什么，不过看起来像是尾插坏了...用充电器是正常的吗？如果充电器正常那有可能是充电宝是QC协议的18w，而手机是PD协议的18w，导致了无法用18w充电，换一个支持更多协议的充电宝试试？ 
&mdash;

**Comment by iyutong** [comment]
那应该就是QC协议问题了


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月29日(周二) 晚上9:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chase535/turbo-charge] 这个模块支持KernelSU吗？ (Issue #87)




 这我确实也没遇到过，不知道为什么，不过看起来像是尾插坏了...用充电器是正常的吗？如果充电器正常那有可能是充电宝是QC协议的18w，而手机是PD协议的18w，导致了无法用18w充电，换一个支持更多协议的充电宝试试？ 
&mdash;
